# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camerawindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraWindow(object):
    def setupUi(self, CameraWindow):
        CameraWindow.setObjectName("CameraWindow")
        CameraWindow.resize(651, 432)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CameraWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cameraOutput = QVideoWidget(CameraWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraOutput.sizePolicy().hasHeightForWidth())
        self.cameraOutput.setSizePolicy(sizePolicy)
        self.cameraOutput.setObjectName("cameraOutput")
        self.horizontalLayout.addWidget(self.cameraOutput)
        self.containerWidget = QtWidgets.QWidget(CameraWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.containerWidget.sizePolicy().hasHeightForWidth())
        self.containerWidget.setSizePolicy(sizePolicy)
        self.containerWidget.setObjectName("containerWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.containerWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraInputLabel = QtWidgets.QLabel(self.containerWidget)
        self.cameraInputLabel.setObjectName("cameraInputLabel")
        self.verticalLayout.addWidget(self.cameraInputLabel)
        self.cameraInput = QtWidgets.QComboBox(self.containerWidget)
        self.cameraInput.setObjectName("cameraInput")
        self.verticalLayout.addWidget(self.cameraInput)
        self.objectInputLabel = QtWidgets.QLabel(self.containerWidget)
        self.objectInputLabel.setObjectName("objectInputLabel")
        self.verticalLayout.addWidget(self.objectInputLabel)
        self.objectInput = QtWidgets.QLineEdit(self.containerWidget)
        self.objectInput.setObjectName("objectInput")
        self.verticalLayout.addWidget(self.objectInput)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.captureBtn = QtWidgets.QPushButton(self.containerWidget)
        self.captureBtn.setObjectName("captureBtn")
        self.verticalLayout.addWidget(self.captureBtn)
        self.horizontalLayout.addWidget(self.containerWidget)

        self.retranslateUi(CameraWindow)
        QtCore.QMetaObject.connectSlotsByName(CameraWindow)

    def retranslateUi(self, CameraWindow):
        _translate = QtCore.QCoreApplication.translate
        CameraWindow.setWindowTitle(_translate("CameraWindow", "Image Capture"))
        self.cameraInputLabel.setText(_translate("CameraWindow", "Camera"))
        self.objectInputLabel.setText(_translate("CameraWindow", "Object Name"))
        self.captureBtn.setText(_translate("CameraWindow", "Capture!"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
