# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/graphwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphWindow(object):
    def setupUi(self, GraphWindow):
        GraphWindow.setObjectName("GraphWindow")
        GraphWindow.resize(813, 431)
        self.gridLayout = QtWidgets.QGridLayout(GraphWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.inputContainer = QtWidgets.QWidget(GraphWindow)
        self.inputContainer.setMaximumSize(QtCore.QSize(200, 16777215))
        self.inputContainer.setObjectName("inputContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.inputContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(self.inputContainer)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.inputContainer)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.fileInput = QtWidgets.QComboBox(self.inputContainer)
        self.fileInput.setObjectName("fileInput")
        self.verticalLayout.addWidget(self.fileInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.plotBtn = QtWidgets.QPushButton(self.inputContainer)
        self.plotBtn.setObjectName("plotBtn")
        self.verticalLayout.addWidget(self.plotBtn)
        self.gridLayout.addWidget(self.inputContainer, 0, 1, 1, 1)
        self.graphContainer = QtWidgets.QVBoxLayout()
        self.graphContainer.setObjectName("graphContainer")
        self.gridLayout.addLayout(self.graphContainer, 0, 0, 1, 1)

        self.retranslateUi(GraphWindow)
        QtCore.QMetaObject.connectSlotsByName(GraphWindow)

    def retranslateUi(self, GraphWindow):
        _translate = QtCore.QCoreApplication.translate
        GraphWindow.setWindowTitle(_translate("GraphWindow", "Form"))
        self.title.setText(_translate("GraphWindow", "Graph Demo Values"))
        self.label.setText(_translate("GraphWindow", "Picture to graph"))
        self.plotBtn.setText(_translate("GraphWindow", "Plot!"))
