# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/trainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TrainWindow(object):
    def setupUi(self, TrainWindow):
        TrainWindow.setObjectName("TrainWindow")
        TrainWindow.resize(563, 317)
        self.closeBtn = QtWidgets.QPushButton(TrainWindow)
        self.closeBtn.setGeometry(QtCore.QRect(470, 280, 81, 26))
        self.closeBtn.setObjectName("closeBtn")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(TrainWindow)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 10, 541, 261))
        font = QtGui.QFont()
        font.setFamily("Andale Mono")
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.trainBtn = QtWidgets.QPushButton(TrainWindow)
        self.trainBtn.setGeometry(QtCore.QRect(10, 280, 121, 26))
        self.trainBtn.setObjectName("trainBtn")

        self.retranslateUi(TrainWindow)
        QtCore.QMetaObject.connectSlotsByName(TrainWindow)

    def retranslateUi(self, TrainWindow):
        _translate = QtCore.QCoreApplication.translate
        TrainWindow.setWindowTitle(_translate("TrainWindow", "Model Trainer"))
        self.closeBtn.setText(_translate("TrainWindow", "Close"))
        self.trainBtn.setText(_translate("TrainWindow", "Start Training"))
